# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 265a7d9d61530d0499cb76d670efd1d8d00635a8322e0615a8014dafa2b8d06eeecd35026347daf14d28d2c4b675fe9e4524ab5aa27e4c45787afd90a5bd7257

test:
  secret_key_base: 00546e5a3317b9d4299e39dd557db78e7e71c4338590fa19a43b46178f0c2598e4ab0de6644b54517b84f38acc7624485da42d6601c92da86700cd589bec1481

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
